In [2]:
import pygrib
import os
import sys
import pickle
import numpy as np
import pandas as pd

In [13]:
import pickle

with open('rawdata/20210101/2021010100_WSEuro4_temperature_sl_1000hPa_001054.pk', 'rb') as file:
    data = pickle.load(file)

In [14]:
for each in data:
    print(each)
    print('-'*20)
    print(each[0])
    print('-'*20)
    print(each[1])
    break

('1:Temperature:K (instant):regular_ll:isobaricInhPa:level 1000:fcst time 1 hrs:from 202101010000', array([[287.375, 287.5  , 287.5  , ..., 289.5  , 289.   , 288.75 ],
       [287.375, 287.375, 287.375, ..., 289.125, 288.875, 288.5  ],
       [287.375, 287.375, 287.375, ..., 288.75 , 288.5  , 288.25 ],
       ...,
       [268.625, 268.625, 268.625, ..., 264.625, 264.625, 264.625],
       [268.625, 268.625, 268.625, ..., 264.625, 264.75 , 264.625],
       [268.625, 268.625, 268.625, ..., 264.75 , 264.75 , 264.75 ]]))
--------------------
1:Temperature:K (instant):regular_ll:isobaricInhPa:level 1000:fcst time 1 hrs:from 202101010000
--------------------
[[287.375 287.5   287.5   ... 289.5   289.    288.75 ]
 [287.375 287.375 287.375 ... 289.125 288.875 288.5  ]
 [287.375 287.375 287.375 ... 288.75  288.5   288.25 ]
 ...
 [268.625 268.625 268.625 ... 264.625 264.625 264.625]
 [268.625 268.625 268.625 ... 264.625 264.75  264.625]
 [268.625 268.625 268.625 ... 264.75  264.75  264.75 ]]


In [10]:
pd.read_csv('rawdata/lon.csv',header=None)

0      1      2      3      4     5      6      7      8      9     ...  \
0   -14.0 -13.96 -13.92 -13.88 -13.84 -13.8 -13.76 -13.72 -13.68 -13.64  ...   
1   -14.0 -13.96 -13.92 -13.88 -13.84 -13.8 -13.76 -13.72 -13.68 -13.64  ...   
2   -14.0 -13.96 -13.92 -13.88 -13.84 -13.8 -13.76 -13.72 -13.68 -13.64  ...   
3   -14.0 -13.96 -13.92 -13.88 -13.84 -13.8 -13.76 -13.72 -13.68 -13.64  ...   
4   -14.0 -13.96 -13.92 -13.88 -13.84 -13.8 -13.76 -13.72 -13.68 -13.64  ...   
..    ...    ...    ...    ...    ...   ...    ...    ...    ...    ...  ...   
872 -14.0 -13.96 -13.92 -13.88 -13.84 -13.8 -13.76 -13.72 -13.68 -13.64  ...   
873 -14.0 -13.96 -13.92 -13.88 -13.84 -13.8 -13.76 -13.72 -13.68 -13.64  ...   
874 -14.0 -13.96 -13.92 -13.88 -13.84 -13.8 -13.76 -13.72 -13.68 -13.64  ...   
875 -14.0 -13.96 -13.92 -13.88 -13.84 -13.8 -13.76 -13.72 -13.68 -13.64  ...   
876 -14.0 -13.96 -13.92 -13.88 -13.84 -13.8 -13.76 -13.72 -13.68 -13.64  ...   

      1266   1267   1268   1269  1270   1271   1272   1273   1274  1275  
0    36.64  36.68  36.72  36.76  36.8  36.84  36.88  36.92  36.96  37.0  
1    36.64  36.68  36.72  36.76  36.8  36.84  36.88  36.92  36.96  37.0  
2    36.64  36.68  36.72  36.76  36.8  36.84  36.88  36.92  36.96  37.0  
3    36.64  36.68  36.72  36.76  36.8  36.84  36.88  36.92  36.96  37.0  
4    36.64  36.68  36.72  36.76  36.8  36.84  36.88  36.92  36.96  37.0  
..     ...    ...    ...    ...   ...    ...    ...    ...    ...   ...  
872  36.64  36.68  36.72  36.76  36.8  36.84  36.88  36.92  36.96  37.0  
873  36.64  36.68  36.72  36.76  36.8  36.84  36.88  36.92  36.96  37.0  
874  36.64  36.68  36.72  36.76  36.8  36.84  36.88  36.92  36.96  37.0  
875  36.64  36.68  36.72  36.76  36.8  36.84  36.88  36.92  36.96  37.0  
876  36.64  36.68  36.72  36.76  36.8  36.84  36.88  36.92  36.96  37.0  

[877 rows x 1276 columns]

In [8]:
import os
import zipfile
 
def zipDir(dirpath, outFullName):

    zip = zipfile.ZipFile(outFullName, "w", zipfile.ZIP_DEFLATED)
    for path, dirnames, filenames in os.walk(dirpath):

        fpath = path.replace(dirpath, '')
 
        for filename in filenames:
            zip.write(os.path.join(path, filename), os.path.join(fpath, filename))
    zip.close()
 
 

input_path = "rawdata"
output_path = "rawdata.zip"

zipDir(input_path, output_path)

In [58]:
LAT1 = None
LAT2 = None
LON1 = None
LON2 = None

def process_message(grb, outfile):
    tmps = "%s" % grb
    wtitle = tmps.split(':')[1]
    wtime = tmps.split(':')[len(tmps.split(':'))-1].split(' ')[1]
    data, lat, lons = grb.data(LAT1, LAT2, LON1, LON2)
    for i in range(len(data)):
        tdata = data[i]
        tlat = lat[i]
        tlon = lons[1]
        for j in range(len(tdata)):
            wdata = tdata[j]
            wlat = tlat[j]
            wlon = tlon[j]
            outfile.write("%s, %s, %s, %s, %s\n" % (wtitle, wtime, wlat, wlon, wdata)) 

In [5]:
LAT, LON = None, None

In [15]:
np.savetxt("csv/lat.csv", LAT, delimiter=",")
np.savetxt("csv/lon.csv", LON, delimiter=",")

In [17]:
df = []
#sys.getsizeof(df)

In [ ]:
with open("csv/data.pk", "wb") as file:
    pickle.dump(df, file)

In [7]:
for filename in os.listdir('winddata/20210101'):
    grbs = pygrib.open('winddata/20210101/'+filename)
    
    in_df = []
    print('#'*30)
    print(filename)

    
    for grb in grbs:
#         wtitle = tmps.split(':')[1]
#         wtime = tmps.split(':')[len(tmps.split(':'))-1].split(' ')[1]
        
        data, lat, lon = grb.data(None, None, None, None)
        
#         if not (np.array_equal(LAT,lat) and np.array_equal(LON,lon)):
#             print('Fuck!')
        
        in_df.append(("%s" % grb, data))
        
    with open('csv/20210101/'+filename.split('.')[0]+'.pk', 'wb') as file:
        pickle.dump(in_df, file)
        
        
#     df.append((filename,in_df))
        
#         lats, lons = grb.latlons()
#         #print(lats, lons)
#         if lats.shape != (877, 1276) or lons.shape != (877, 1276):
#             print(lats.shape, lons.shape)
#             print('-'*20)
    

##############################
2021010118_WSEuro4_wind_u_sl_1000hPa_001054.grib
##############################
2021010112_WSEuro4_wind_v_sl_1000hPa_001054.grib
##############################
2021010118_WSEuro4_wind_w_sl_1000hPa_001054.grib
##############################
2021010106_WSEuro4_wind_u_sl_1000hPa_001054.grib
##############################
2021010100_WSEuro4_wind_w_sl_1000hPa_001054.grib
##############################
2021010100_WSEuro4_wind_v_sl_1000hPa_001054.grib
##############################
2021010106_WSEuro4_wind_v_sl_1000hPa_001054.grib
##############################
2021010112_WSEuro4_wind_w_sl_1000hPa_001054.grib
##############################
2021010100_WSEuro4_wind_u_sl_1000hPa_001054.grib
##############################
2021010106_WSEuro4_temperature_sl_1000hPa_001054.grib
##############################
2021010118_WSEuro4_temperature_sl_1000hPa_001054.grib
##############################
2021010112_WSEuro4_wind_u_sl_1000hPa_001054.grib
##############################

In [46]:
# grbs.readline()

for grb in grbs:
    tmps = "%s" % grb
    wtitle = tmps.split(':')[1]
    wtime = tmps.split(':')[len(tmps.split(':'))-1].split(' ')[1]
    
    print(tmps)
    print(wtitle)
    print(wtime)
    
    print('-'*20)
#     print(grb)
#     lats, lons = grb.latlons()
#     print(lats, lons)
#     print(lats.shape, lons.shape)

2:None Vertical velocity m s**-1:unknown (instant):regular_ll:isobaricInhPa:level 1000:fcst time 6 hrs:from 202101020600
None Vertical velocity m s**-1
202101020600
--------------------
3:None Vertical velocity m s**-1:unknown (instant):regular_ll:isobaricInhPa:level 1000:fcst time 9 hrs:from 202101020600
None Vertical velocity m s**-1
202101020600
--------------------
4:None Vertical velocity m s**-1:unknown (instant):regular_ll:isobaricInhPa:level 1000:fcst time 12 hrs:from 202101020600
None Vertical velocity m s**-1
202101020600
--------------------
5:None Vertical velocity m s**-1:unknown (instant):regular_ll:isobaricInhPa:level 1000:fcst time 15 hrs:from 202101020600
None Vertical velocity m s**-1
202101020600
--------------------
6:None Vertical velocity m s**-1:unknown (instant):regular_ll:isobaricInhPa:level 1000:fcst time 18 hrs:from 202101020600
None Vertical velocity m s**-1
202101020600
--------------------
7:None Vertical velocity m s**-1:unknown (instant):regular_ll:isoba

In [68]:
compare_key = []

for grb in grbs:  
    print('-----------')
    print(grb) 
    print('-----------')
    key = grb.keys()
    print(len(key))
    compare_key.append(key)
    print('-----------')
    value = grb.values  
    print(value.shape)
    print(value[0])
    print(value[1])
    print(value[0] == value[1])

-----for分割线------
1:None Vertical velocity m s**-1:unknown (instant):regular_ll:isobaricInhPa:level 1000:fcst time 3 hrs:from 202101020600
-----头文件分割线------
173
-----keyvalue分割线------
(877, 1276)
[0.00211215 0.00211215 0.00211215 ... 0.01773715 0.01773715 0.01773715]
[0.00211215 0.00211215 0.00211215 ... 0.01773715 0.01773715 0.01773715]
[ True  True  True ...  True  True  True]
-----for分割线------
2:None Vertical velocity m s**-1:unknown (instant):regular_ll:isobaricInhPa:level 1000:fcst time 6 hrs:from 202101020600
-----头文件分割线------
173
-----keyvalue分割线------
(877, 1276)
[-0.00154012 -0.00154012 -0.00154012 ...  0.01408488  0.01408488
  0.01408488]
[-0.00154012 -0.00154012 -0.00154012 ...  0.01408488  0.01408488
  0.01408488]
[ True  True  True ...  True  True  True]
-----for分割线------
3:None Vertical velocity m s**-1:unknown (instant):regular_ll:isobaricInhPa:level 1000:fcst time 9 hrs:from 202101020600
-----头文件分割线------
173
-----keyvalue分割线------
(877, 1276)
[0.00456756 0.00456756 0.0

In [49]:
compare_key[16] == compare_key[1]

True